import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";
import colors from "@/config/colors";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen w-full  text-black flex`}
      >
        {/* sidebar */}
        {/* <p className="border">Sidebar</p> */}
        <SideNav />
        {/* main page */}
        <div className={`p-8 w-full bg-[${colors.secondary}]`}>{children}</div>
      </body>
    </html>
  );
}
